package aidetector;

import aidetector.core.Analyzer;
import aidetector.core.FileReport;
import aidetector.core.SourceFile;
import aidetector.input.SourceLoader;
import aidetector.report.ConsoleReport;
import aidetector.report.HtmlReport;
import aidetector.report.ReportRenderer;
import aidetector.signals.DefaultSignals;

import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

public final class Main {

    public static void main(String[] args) {
        Options options;
        try {
            options = Options.parse(args);
        } catch (IllegalArgumentException e) {
            System.err.println("error: " + e.getMessage());
            printUsage(System.err);
            System.exit(2);
            return;
        }

        if (options.help) {
            printUsage(System.out);
            return;
        }
        if (options.target == null) {
            System.err.println("error: no target given - pass a file, a directory, or a GitHub/Git URL");
            System.err.println();
            printUsage(System.err);
            System.exit(2);
            return;
        }

        try {
            Analyzer analyzer = new Analyzer(DefaultSignals.all(), options.aiThreshold, options.mixedThreshold);
            List<SourceFile> sources = new SourceLoader().load(options.target, options.languageHint);

            List<FileReport> reports = new ArrayList<>(sources.size());
            for (SourceFile source : sources) {
                reports.add(new FileReport(source, analyzer.analyze(source)));
            }

            ReportRenderer renderer = switch (options.format) {
                case CONSOLE -> new ConsoleReport(
                        options.aiThreshold, options.mixedThreshold, options.fileLimit, options.evidenceLimit);
                case HTML -> new HtmlReport(options.aiThreshold, options.mixedThreshold, options.evidenceLimit);
            };
            String rendered = renderer.render(reports);
            if (options.output != null) {
                Path output = Path.of(options.output);
                Path parent = output.getParent();
                if (parent != null) {
                    Files.createDirectories(parent);
                }
                Files.writeString(output, rendered, StandardCharsets.UTF_8);
                System.out.println("report written to " + output.toAbsolutePath());
            } else {
                System.out.println(rendered);
            }
        } catch (Exception e) {
            System.err.println("error: " + e.getMessage());
            System.exit(1);
        }
    }

    private static void printUsage(PrintStream out) {
        out.println("""
                aidetect - estimate whether code was written by a human or generated by a model

                Usage:
                  aidetect <target> [options]

                Target:
                  a file, a directory, a GitHub/Git URL, or '-' to read from stdin

                Options:
                  --ai-threshold <n>      score at or above which a file reads as AI (default 50)
                  --mixed-threshold <n>   score at or above which a file reads as mixed (default 25)
                  --top <n>               how many files to detail for a repository (default 10)
                  --evidence <n>          how many evidence lines to show per signal (default 5)
                  --format <name>         report format: console, html (default console)
                  --out <file>            write report to a file instead of printing it
                  --lang <name>           language hint for stdin: java, js, ts, python
                  -h, --help              show this help

                Examples:
                  aidetect ./src
                  aidetect Main.java
                  aidetect ./src --format html --out report.html
                  aidetect https://github.com/owner/repo
                  cat snippet.java | aidetect - --lang java""");
    }

    private enum ReportFormat {
        CONSOLE,
        HTML
    }

    private static final class Options {
        String target;
        String languageHint;
        String output;
        ReportFormat format = ReportFormat.CONSOLE;
        double aiThreshold = 50;
        double mixedThreshold = 25;
        int fileLimit = 10;
        int evidenceLimit = 5;
        boolean help;

        static Options parse(String[] args) {
            Options options = new Options();
            for (int i = 0; i < args.length; i++) {
                String argument = args[i];
                switch (argument) {
                    case "-h", "--help" -> options.help = true;
                    case "--ai-threshold" -> options.aiThreshold = parseDouble(argument, value(args, ++i));
                    case "--mixed-threshold" -> options.mixedThreshold = parseDouble(argument, value(args, ++i));
                    case "--top" -> options.fileLimit = parseInt(argument, value(args, ++i));
                    case "--evidence" -> options.evidenceLimit = parseInt(argument, value(args, ++i));
                    case "--format" -> options.format = parseFormat(value(args, ++i));
                    case "--out" -> options.output = value(args, ++i);
                    case "--lang" -> options.languageHint = value(args, ++i);
                    default -> {
                        if (argument.startsWith("--")) {
                            throw new IllegalArgumentException("unknown option " + argument);
                        }
                        if (options.target == null) {
                            options.target = argument;
                        }
                    }
                }
            }
            if (options.format == ReportFormat.HTML && options.output == null) {
                options.output = "ai-detector-report.html";
            }
            return options;
        }

        private static String value(String[] args, int index) {
            if (index >= args.length) {
                throw new IllegalArgumentException("missing value for " + args[index - 1]);
            }
            return args[index];
        }

        private static double parseDouble(String option, String raw) {
            try {
                return Double.parseDouble(raw);
            } catch (NumberFormatException e) {
                throw new IllegalArgumentException(option + " expects a number, got " + raw);
            }
        }

        private static int parseInt(String option, String raw) {
            try {
                return Integer.parseInt(raw);
            } catch (NumberFormatException e) {
                throw new IllegalArgumentException(option + " expects an integer, got " + raw);
            }
        }

        private static ReportFormat parseFormat(String raw) {
            return switch (raw.toLowerCase()) {
                case "console", "text", "txt" -> ReportFormat.CONSOLE;
                case "html", "web" -> ReportFormat.HTML;
                default -> throw new IllegalArgumentException("--format expects console or html, got " + raw);
            };
        }
    }
}
